/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bracestate.View;

import bracestate.HousingUnitDB;
import bracestate.PropertyDB;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cess Dee
 */
public class Housingunit extends javax.swing.JFrame {

     String conString = "jdbc:postgresql://localhost:5432/Estate";
    String user = "postgres";
    String password = "abel";
    
    ResultSet rs = null;

    
    /**
     * Creates new form Housingunit
     */
    public Housingunit() {
        initComponents();
        
        txtFldHousingUnit.setEditable(false);
        txtFldHUnitName.setEditable(false);
        txtFldLocation.setEditable(false);
        txtFldRoomCategories.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableHousingUnitRooms = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        txtFldHUnitName = new javax.swing.JTextField();
        btnDisplay = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        comboBxCondition = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txtFldHousingUnit = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtFldLocation = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtFldHouseNumber = new javax.swing.JTextField();
        txtFldRentCharge = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtFldRoomCategories = new javax.swing.JTextField();
        comboBxStatus = new javax.swing.JComboBox();
        btnHuosingUnitExit = new javax.swing.JButton();
        txtFldTenantName = new javax.swing.JTextField();
        btnRetrieve = new javax.swing.JButton();

        setTitle("ACO HOLDINGS LIMITED - ROOMS ALLOCATION");

        tableHousingUnitRooms.setBackground(new java.awt.Color(0, 255, 213));
        tableHousingUnitRooms.setForeground(new java.awt.Color(0, 0, 153));
        tableHousingUnitRooms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableHousingUnitRooms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableHousingUnitRoomsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableHousingUnitRooms);

        jPanel2.setPreferredSize(new java.awt.Dimension(216, 400));

        btnDisplay.setBackground(new java.awt.Color(255, 255, 0));
        btnDisplay.setText("Display");
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("Rent Charge");

        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Condition");

        btnCreate.setBackground(new java.awt.Color(255, 255, 0));
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        comboBxCondition.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Good", "Bad", "Undergoing Repair", "Undergoing Construction", "Out of Service" }));

        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("House Number");

        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Housing unit");

        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Room Categories");

        btnReset.setBackground(new java.awt.Color(255, 255, 0));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("Status");

        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Housing unit Name");

        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setText("Location");

        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("Tenant Name");

        comboBxStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vacant", "Occupied" }));

        btnHuosingUnitExit.setBackground(new java.awt.Color(255, 255, 0));
        btnHuosingUnitExit.setText("Exit");
        btnHuosingUnitExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuosingUnitExitActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(txtFldHUnitName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnDisplay, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnCreate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(comboBxCondition, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtFldHousingUnit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtFldLocation, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnReset, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtFldHouseNumber, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtFldRentCharge, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtFldRoomCategories, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(comboBxStatus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnHuosingUnitExit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtFldTenantName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(119, 119, 119))
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtFldHUnitName, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtFldHousingUnit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtFldLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFldHouseNumber)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboBxStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboBxCondition, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFldRoomCategories)
                            .addComponent(txtFldRentCharge)
                            .addComponent(txtFldTenantName)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnCreate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDisplay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnHuosingUnitExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(49, 49, 49))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFldHousingUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFldHUnitName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(txtFldLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtFldRoomCategories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(14, 14, 14)
                        .addComponent(txtFldHouseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(14, 14, 14)
                        .addComponent(comboBxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDisplay)
                        .addGap(34, 34, 34)
                        .addComponent(btnCreate)
                        .addGap(40, 40, 40)
                        .addComponent(btnReset)
                        .addGap(43, 43, 43)
                        .addComponent(btnHuosingUnitExit)
                        .addGap(19, 19, 19)))
                .addComponent(comboBxCondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFldRentCharge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFldTenantName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnRetrieve.setBackground(new java.awt.Color(255, 255, 0));
        btnRetrieve.setText("Retrieve");
        btnRetrieve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrieveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRetrieve, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRetrieve)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public String getHUnit()
    {
        return txtFldHousingUnit.toString();
    }
    
    public String getHUnitName()
    {
        return txtFldHUnitName.toString();
    }
    
    public String getLocatio()
    {
        return txtFldLocation.toString();
    }
    
    public String getRoomCategories()
    {
        return txtFldRoomCategories.toString();
    }
    
    
    public String getHNumber()
    {
        return txtFldHouseNumber.toString();
    }
    
    public String getStatus()
    {
        return comboBxStatus.toString();
    }
    
    public String getCondition()
    {
        return comboBxCondition.toString();
    }
    
    public double getRent()
    {
        return Double.parseDouble(txtFldRentCharge.getText());
    }
    
    public String getTenant()
    {
        return txtFldTenantName.toString();
    }
    
    public void resetFields()
    {
        txtFldHousingUnit.setText("");
        txtFldHUnitName.setText("");
        txtFldLocation.setText("");
        txtFldRoomCategories.setText("");
        txtFldHouseNumber.setText("");
        comboBxStatus.setSelectedItem("");
        comboBxCondition.setSelectedItem("");
        txtFldRentCharge.setText("");
        txtFldTenantName.setText("");
    }
    
    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
        DisplayHousingUnitRooms disp = new DisplayHousingUnitRooms();
        disp.show();
        
    }//GEN-LAST:event_btnDisplayActionPerformed

    private void tableHousingUnitRoomsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableHousingUnitRoomsMouseClicked
       
        try {
            String id = tableHousingUnitRooms.getValueAt(tableHousingUnitRooms.getSelectedRow(), 0).toString();
            String hunit = tableHousingUnitRooms.getValueAt(tableHousingUnitRooms.getSelectedRow(), 1).toString();
            String hunitname = tableHousingUnitRooms.getValueAt(tableHousingUnitRooms.getSelectedRow(), 2).toString();
            String location = tableHousingUnitRooms.getValueAt(tableHousingUnitRooms.getSelectedRow(), 3).toString();
            String categories = tableHousingUnitRooms.getValueAt(tableHousingUnitRooms.getSelectedRow(), 4).toString();
            
            txtFldHousingUnit.setText(hunit);
            txtFldHUnitName.setText(hunitname);
            txtFldLocation.setText(location);
            txtFldRoomCategories.setText(categories);

        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Error in Selection!!", "Access Denied", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_tableHousingUnitRoomsMouseClicked

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        
        try {
            HousingUnitDB hDB = new HousingUnitDB();

            if (txtFldHousingUnit.getText().length() == 0) {
                JOptionPane.showMessageDialog(null, " Housing unit should not be blank!", "Error!", JOptionPane.OK_OPTION);
                txtFldHousingUnit.requestFocus();
            } else if (txtFldHUnitName.getText().length() == 0) {

                JOptionPane.showMessageDialog(null, " Housing unit name should not be blank!", "Error!", JOptionPane.OK_OPTION);
                txtFldHUnitName.requestFocus();
            } else if (txtFldLocation.getText().length() == 0) {

                JOptionPane.showMessageDialog(null, " Location should not be blank!", "Error!", JOptionPane.OK_OPTION);
                txtFldLocation.requestFocus();
            } else if (txtFldRoomCategories.getText().length() == 0) {

                JOptionPane.showMessageDialog(null, " Room categories should not be blank!", "Error!", JOptionPane.OK_OPTION);
                txtFldRoomCategories.requestFocus();
            }
            else if ( txtFldHouseNumber.getText().length() == 0) {

                JOptionPane.showMessageDialog(null, "House Number should not be blank!", "Error!", JOptionPane.OK_OPTION);
                 txtFldHouseNumber.requestFocus();
            }
            else if (comboBxStatus.getSelectedItem().toString().length() == 0) {

                JOptionPane.showMessageDialog(null, " Status should not be blank!", "Error!", JOptionPane.OK_OPTION);
                comboBxStatus.requestFocus();
            }
            else if (comboBxCondition.getSelectedItem().toString().length() == 0) {

                JOptionPane.showMessageDialog(null, " Condition should not be blank!", "Error!", JOptionPane.OK_OPTION);
                comboBxCondition.requestFocus();
            }
            else if (txtFldRentCharge.getText().length() == 0) {

                JOptionPane.showMessageDialog(null, " Rent charge should not be blank!", "Error!", JOptionPane.OK_OPTION);
                txtFldRentCharge.requestFocus();
            }
            else if (hDB.addHousingUnit(txtFldHousingUnit.getText(), txtFldHUnitName.getText(), txtFldLocation.getText(), txtFldRoomCategories.getText(), txtFldHouseNumber.getText(), comboBxStatus.getSelectedItem().toString(), comboBxCondition.getSelectedItem().toString(), txtFldRentCharge.getText(), txtFldTenantName.getText())) {
                JOptionPane.showMessageDialog(null, "New Room registered Successfully!");

                resetFields();
            } else {
                JOptionPane.showMessageDialog(null, "Incorrect values!", "Error!", JOptionPane.OK_OPTION);

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Incorrect values!", "Error!", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        resetFields();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnHuosingUnitExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuosingUnitExitActionPerformed
        int answer = JOptionPane.showConfirmDialog(this, "Exit?", "Confirm Exit!", JOptionPane.YES_NO_OPTION);
        if (answer == JOptionPane.YES_NO_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_btnHuosingUnitExitActionPerformed

    private void btnRetrieveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrieveActionPerformed
        DefaultTableModel dm = getData();
        tableHousingUnitRooms.setModel(dm);
    }//GEN-LAST:event_btnRetrieveActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public DefaultTableModel getData() {
        //Add columns to TableModel
        DefaultTableModel dm = new DefaultTableModel();

        dm.addColumn("Hid");
        dm.addColumn("Housing Unit");
        dm.addColumn("Name");
        dm.addColumn("Location");
        dm.addColumn("Category");

        //Select
        String sql = "SELECT * FROM property";

        try {
            Class.forName("org.postgresql.Driver");
            Connection conn = DriverManager.getConnection(conString, user, password);

            //Prepared statement
           
            PreparedStatement st = conn.prepareStatement(sql);

            //st.execute();
            
            ResultSet rt = st.executeQuery();

            while (rt.next()) {
                String id = rt.getString(1);
                String hUnit = rt.getString(2);
                String name = rt.getString(3);
                String location = rt.getString(4);
                String category = rt.getString(5);
               
                dm.addRow(new String[]{id,hUnit,name,location,category});
             
            }
            return dm;
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return null;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Housingunit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Housingunit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Housingunit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Housingunit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Housingunit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnHuosingUnitExit;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnRetrieve;
    private javax.swing.JComboBox comboBxCondition;
    private javax.swing.JComboBox comboBxStatus;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableHousingUnitRooms;
    private javax.swing.JTextField txtFldHUnitName;
    private javax.swing.JTextField txtFldHouseNumber;
    private javax.swing.JTextField txtFldHousingUnit;
    private javax.swing.JTextField txtFldLocation;
    private javax.swing.JTextField txtFldRentCharge;
    private javax.swing.JTextField txtFldRoomCategories;
    private javax.swing.JTextField txtFldTenantName;
    // End of variables declaration//GEN-END:variables
}
