package bracestate.View;

/**
 *
 * @author Abi
 */
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Roles extends javax.swing.JFrame {

    public Roles() {
        initComponents();
    }

    LoginRoles lRoles = new LoginRoles();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAccountant = new javax.swing.JMenu();
        btnAccountantTasks = new javax.swing.JMenu();
        btnAccountantAccounting = new javax.swing.JMenu();
        btnAccountantArrears = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        btnAccountantExpenditure = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        btnAccountantRentPayment = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        menuAccountantNewTenant = new javax.swing.JMenuItem();
        jSeparator47 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();
        btnAccountantPrintReceipt = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        btnAccountantDefaultNotice = new javax.swing.JMenuItem();
        jSeparator42 = new javax.swing.JPopupMenu.Separator();
        menuAccountantIDVerification = new javax.swing.JMenuItem();
        jSeparator49 = new javax.swing.JPopupMenu.Separator();
        menuAccountantHunits = new javax.swing.JMenuItem();
        jSeparator50 = new javax.swing.JPopupMenu.Separator();
        menuAccountanttProperty = new javax.swing.JMenuItem();
        jSeparator51 = new javax.swing.JPopupMenu.Separator();
        menuAccounantTenants = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        menuAccExit = new javax.swing.JMenuItem();
        menuAdmin = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        menuAdminArrears = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        menuAdminExpenditure = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        menuAdminRentPayment = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        menuAdminIncome = new javax.swing.JMenuItem();
        jSeparator17 = new javax.swing.JPopupMenu.Separator();
        jSeparator48 = new javax.swing.JPopupMenu.Separator();
        jMenu10 = new javax.swing.JMenu();
        menuAdminPaymentsReport = new javax.swing.JMenuItem();
        menuAdminExpenditureReport = new javax.swing.JMenuItem();
        menuAdminArrearsReport = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        menuAdminHunits = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        menuNewTenant = new javax.swing.JMenuItem();
        jSeparator15 = new javax.swing.JPopupMenu.Separator();
        menuAdminProperty = new javax.swing.JMenuItem();
        jSeparator16 = new javax.swing.JPopupMenu.Separator();
        menuAdminTenants = new javax.swing.JMenuItem();
        jSeparator18 = new javax.swing.JPopupMenu.Separator();
        jMenu6 = new javax.swing.JMenu();
        menuAdminPayments = new javax.swing.JMenuItem();
        jSeparator19 = new javax.swing.JPopupMenu.Separator();
        menuAdminRentDefaultNotice = new javax.swing.JMenuItem();
        jSeparator43 = new javax.swing.JPopupMenu.Separator();
        menuAdminIDVerification = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        menuAdminCreateuserAccount = new javax.swing.JMenuItem();
        jSeparator23 = new javax.swing.JPopupMenu.Separator();
        menuAdminChangePassword = new javax.swing.JMenuItem();
        jSeparator46 = new javax.swing.JPopupMenu.Separator();
        btnAdminExit = new javax.swing.JMenuItem();
        menuagent = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu7 = new javax.swing.JMenu();
        menuAgentArrears = new javax.swing.JMenuItem();
        jSeparator24 = new javax.swing.JPopupMenu.Separator();
        menuAgentExpenditure = new javax.swing.JMenuItem();
        jSeparator25 = new javax.swing.JPopupMenu.Separator();
        menuAgentRentPayment = new javax.swing.JMenuItem();
        jSeparator26 = new javax.swing.JPopupMenu.Separator();
        jSeparator31 = new javax.swing.JPopupMenu.Separator();
        menuAgentHunits = new javax.swing.JMenuItem();
        jSeparator32 = new javax.swing.JPopupMenu.Separator();
        menuAgentNewTenant = new javax.swing.JMenuItem();
        jSeparator33 = new javax.swing.JPopupMenu.Separator();
        menuAgentProperty = new javax.swing.JMenuItem();
        jSeparator34 = new javax.swing.JPopupMenu.Separator();
        menuAgentTenants = new javax.swing.JMenuItem();
        jSeparator35 = new javax.swing.JPopupMenu.Separator();
        jMenu8 = new javax.swing.JMenu();
        menuAgentPayments = new javax.swing.JMenuItem();
        jSeparator30 = new javax.swing.JPopupMenu.Separator();
        menuAgentRentDefaultNotice = new javax.swing.JMenuItem();
        jSeparator44 = new javax.swing.JPopupMenu.Separator();
        menuAgentIDVerification = new javax.swing.JMenuItem();
        jSeparator21 = new javax.swing.JPopupMenu.Separator();
        btnAgentExit = new javax.swing.JMenuItem();
        menucaretaker = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menuCaretakerAccounting = new javax.swing.JMenu();
        menuCaretakerArrears = new javax.swing.JMenuItem();
        jSeparator27 = new javax.swing.JPopupMenu.Separator();
        menuCaretakerExpenditure = new javax.swing.JMenuItem();
        jSeparator28 = new javax.swing.JPopupMenu.Separator();
        menuCaretakerRentPayment = new javax.swing.JMenuItem();
        jSeparator29 = new javax.swing.JPopupMenu.Separator();
        jSeparator41 = new javax.swing.JPopupMenu.Separator();
        menuCaretakerHunits = new javax.swing.JMenuItem();
        jSeparator40 = new javax.swing.JPopupMenu.Separator();
        menuCaretakerNewTenant = new javax.swing.JMenuItem();
        jSeparator39 = new javax.swing.JPopupMenu.Separator();
        menuCaretakerProperty = new javax.swing.JMenuItem();
        jSeparator38 = new javax.swing.JPopupMenu.Separator();
        menuCaretakerTenants = new javax.swing.JMenuItem();
        jSeparator37 = new javax.swing.JPopupMenu.Separator();
        jMenu9 = new javax.swing.JMenu();
        menuCaretakerPayments = new javax.swing.JMenuItem();
        jSeparator36 = new javax.swing.JPopupMenu.Separator();
        menuCaretakerRentDefaultNotice = new javax.swing.JMenuItem();
        jSeparator45 = new javax.swing.JPopupMenu.Separator();
        menuCaretakerIDVerification = new javax.swing.JMenuItem();
        jSeparator22 = new javax.swing.JPopupMenu.Separator();
        menuCaretakerExit = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenu();
        btnAboutBracestate = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jSeparator20 = new javax.swing.JPopupMenu.Separator();
        jMenuItem19 = new javax.swing.JMenuItem();
        menuLogout = new javax.swing.JMenu();
        menuSignOut = new javax.swing.JMenuItem();

        setTitle("BRACESTATE - DASHBOARD");
        setResizable(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Copyright: (C) 2017 All Rights Reserved");

        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(354, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(344, 344, 344))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(573, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        menuAccountant.setText("Accountant");

        btnAccountantTasks.setText("Tasks");

        btnAccountantAccounting.setText("Accounting");

        btnAccountantArrears.setText("Arrears");
        btnAccountantArrears.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountantArrearsActionPerformed(evt);
            }
        });
        btnAccountantAccounting.add(btnAccountantArrears);
        btnAccountantAccounting.add(jSeparator5);

        btnAccountantExpenditure.setText("Expenditure");
        btnAccountantExpenditure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountantExpenditureActionPerformed(evt);
            }
        });
        btnAccountantAccounting.add(btnAccountantExpenditure);
        btnAccountantAccounting.add(jSeparator3);

        btnAccountantRentPayment.setText("Rent Payment");
        btnAccountantRentPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountantRentPaymentActionPerformed(evt);
            }
        });
        btnAccountantAccounting.add(btnAccountantRentPayment);
        btnAccountantAccounting.add(jSeparator4);

        btnAccountantTasks.add(btnAccountantAccounting);
        btnAccountantTasks.add(jSeparator7);

        menuAccountantNewTenant.setText("New Tenant");
        menuAccountantNewTenant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAccountantNewTenantActionPerformed(evt);
            }
        });
        btnAccountantTasks.add(menuAccountantNewTenant);
        btnAccountantTasks.add(jSeparator47);

        jMenu3.setText("Print");

        btnAccountantPrintReceipt.setText("Print Receipt");
        btnAccountantPrintReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountantPrintReceiptActionPerformed(evt);
            }
        });
        jMenu3.add(btnAccountantPrintReceipt);
        jMenu3.add(jSeparator8);

        btnAccountantDefaultNotice.setText("Print Rent Default Notice");
        btnAccountantDefaultNotice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountantDefaultNoticeActionPerformed(evt);
            }
        });
        jMenu3.add(btnAccountantDefaultNotice);

        btnAccountantTasks.add(jMenu3);
        btnAccountantTasks.add(jSeparator42);

        menuAccountantIDVerification.setText("ID Verification");
        menuAccountantIDVerification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAccountantIDVerificationActionPerformed(evt);
            }
        });
        btnAccountantTasks.add(menuAccountantIDVerification);
        btnAccountantTasks.add(jSeparator49);

        menuAccountantHunits.setText("Housing units");
        menuAccountantHunits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAccountantHunitsActionPerformed(evt);
            }
        });
        btnAccountantTasks.add(menuAccountantHunits);
        btnAccountantTasks.add(jSeparator50);

        menuAccountanttProperty.setText("Property");
        menuAccountanttProperty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAccountanttPropertyActionPerformed(evt);
            }
        });
        btnAccountantTasks.add(menuAccountanttProperty);
        btnAccountantTasks.add(jSeparator51);

        menuAccounantTenants.setText("Tenants");
        menuAccounantTenants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAccounantTenantsActionPerformed(evt);
            }
        });
        btnAccountantTasks.add(menuAccounantTenants);

        menuAccountant.add(btnAccountantTasks);
        menuAccountant.add(jSeparator6);

        menuAccExit.setText("Exit");
        menuAccExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAccExitActionPerformed(evt);
            }
        });
        menuAccountant.add(menuAccExit);

        jMenuBar1.add(menuAccountant);

        menuAdmin.setText("Admin");
        menuAdmin.add(jSeparator1);

        jMenu4.setText("Tasks");

        jMenu5.setText("Accounting");

        menuAdminArrears.setText("Arrears");
        menuAdminArrears.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdminArrearsActionPerformed(evt);
            }
        });
        jMenu5.add(menuAdminArrears);
        jMenu5.add(jSeparator11);

        menuAdminExpenditure.setText("Expenditure");
        menuAdminExpenditure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdminExpenditureActionPerformed(evt);
            }
        });
        jMenu5.add(menuAdminExpenditure);
        jMenu5.add(jSeparator12);

        menuAdminRentPayment.setText("Rent Payment");
        menuAdminRentPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdminRentPaymentActionPerformed(evt);
            }
        });
        jMenu5.add(menuAdminRentPayment);
        jMenu5.add(jSeparator13);

        menuAdminIncome.setText("Income");
        menuAdminIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdminIncomeActionPerformed(evt);
            }
        });
        jMenu5.add(menuAdminIncome);
        jMenu5.add(jSeparator17);
        jMenu5.add(jSeparator48);

        jMenu10.setText("Reports");

        menuAdminPaymentsReport.setText("Generate Payments Report");
        menuAdminPaymentsReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdminPaymentsReportActionPerformed(evt);
            }
        });
        jMenu10.add(menuAdminPaymentsReport);

        menuAdminExpenditureReport.setText("Generate Expenditure Report");
        menuAdminExpenditureReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdminExpenditureReportActionPerformed(evt);
            }
        });
        jMenu10.add(menuAdminExpenditureReport);

        menuAdminArrearsReport.setText("Generate Arrears Report");
        menuAdminArrearsReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdminArrearsReportActionPerformed(evt);
            }
        });
        jMenu10.add(menuAdminArrearsReport);

        jMenu5.add(jMenu10);

        jMenu4.add(jMenu5);
        jMenu4.add(jSeparator10);

        menuAdminHunits.setText("Housing units");
        menuAdminHunits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdminHunitsActionPerformed(evt);
            }
        });
        jMenu4.add(menuAdminHunits);
        jMenu4.add(jSeparator14);

        menuNewTenant.setText("New Tenant");
        menuNewTenant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNewTenantActionPerformed(evt);
            }
        });
        jMenu4.add(menuNewTenant);
        jMenu4.add(jSeparator15);

        menuAdminProperty.setText("Property");
        menuAdminProperty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdminPropertyActionPerformed(evt);
            }
        });
        jMenu4.add(menuAdminProperty);
        jMenu4.add(jSeparator16);

        menuAdminTenants.setText("Tenants");
        menuAdminTenants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdminTenantsActionPerformed(evt);
            }
        });
        jMenu4.add(menuAdminTenants);
        jMenu4.add(jSeparator18);

        jMenu6.setText("Print");

        menuAdminPayments.setText("Print Receipt");
        menuAdminPayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdminPaymentsActionPerformed(evt);
            }
        });
        jMenu6.add(menuAdminPayments);
        jMenu6.add(jSeparator19);

        menuAdminRentDefaultNotice.setText("Print Rent Default Notice");
        menuAdminRentDefaultNotice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdminRentDefaultNoticeActionPerformed(evt);
            }
        });
        jMenu6.add(menuAdminRentDefaultNotice);

        jMenu4.add(jMenu6);
        jMenu4.add(jSeparator43);

        menuAdminIDVerification.setText("ID Verification");
        menuAdminIDVerification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdminIDVerificationActionPerformed(evt);
            }
        });
        jMenu4.add(menuAdminIDVerification);

        menuAdmin.add(jMenu4);
        menuAdmin.add(jSeparator9);

        menuAdminCreateuserAccount.setText("Create User Account");
        menuAdminCreateuserAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdminCreateuserAccountActionPerformed(evt);
            }
        });
        menuAdmin.add(menuAdminCreateuserAccount);
        menuAdmin.add(jSeparator23);

        menuAdminChangePassword.setText("Change Account Password");
        menuAdminChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdminChangePasswordActionPerformed(evt);
            }
        });
        menuAdmin.add(menuAdminChangePassword);
        menuAdmin.add(jSeparator46);

        btnAdminExit.setText("Exit");
        btnAdminExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminExitActionPerformed(evt);
            }
        });
        menuAdmin.add(btnAdminExit);

        jMenuBar1.add(menuAdmin);

        menuagent.setText("Agent");

        jMenu1.setText("Tasks");
        jMenu1.add(jSeparator2);

        jMenu7.setText("Accounting");

        menuAgentArrears.setText("Arrears");
        menuAgentArrears.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAgentArrearsActionPerformed(evt);
            }
        });
        jMenu7.add(menuAgentArrears);
        jMenu7.add(jSeparator24);

        menuAgentExpenditure.setText("Expenditure");
        menuAgentExpenditure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAgentExpenditureActionPerformed(evt);
            }
        });
        jMenu7.add(menuAgentExpenditure);
        jMenu7.add(jSeparator25);

        menuAgentRentPayment.setText("Rent Payment");
        menuAgentRentPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAgentRentPaymentActionPerformed(evt);
            }
        });
        jMenu7.add(menuAgentRentPayment);
        jMenu7.add(jSeparator26);

        jMenu1.add(jMenu7);
        jMenu1.add(jSeparator31);

        menuAgentHunits.setText("Housing units");
        menuAgentHunits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAgentHunitsActionPerformed(evt);
            }
        });
        jMenu1.add(menuAgentHunits);
        jMenu1.add(jSeparator32);

        menuAgentNewTenant.setText("New Tenant");
        menuAgentNewTenant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAgentNewTenantActionPerformed(evt);
            }
        });
        jMenu1.add(menuAgentNewTenant);
        jMenu1.add(jSeparator33);

        menuAgentProperty.setText("Property");
        menuAgentProperty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAgentPropertyActionPerformed(evt);
            }
        });
        jMenu1.add(menuAgentProperty);
        jMenu1.add(jSeparator34);

        menuAgentTenants.setText("Tenants");
        menuAgentTenants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAgentTenantsActionPerformed(evt);
            }
        });
        jMenu1.add(menuAgentTenants);
        jMenu1.add(jSeparator35);

        jMenu8.setText("Print");

        menuAgentPayments.setText("Print Receipt");
        menuAgentPayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAgentPaymentsActionPerformed(evt);
            }
        });
        jMenu8.add(menuAgentPayments);
        jMenu8.add(jSeparator30);

        menuAgentRentDefaultNotice.setText("Print Rent Default Notice");
        menuAgentRentDefaultNotice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAgentRentDefaultNoticeActionPerformed(evt);
            }
        });
        jMenu8.add(menuAgentRentDefaultNotice);

        jMenu1.add(jMenu8);
        jMenu1.add(jSeparator44);

        menuAgentIDVerification.setText("ID Verification");
        menuAgentIDVerification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAgentIDVerificationActionPerformed(evt);
            }
        });
        jMenu1.add(menuAgentIDVerification);

        menuagent.add(jMenu1);
        menuagent.add(jSeparator21);

        btnAgentExit.setText("Exit");
        btnAgentExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgentExitActionPerformed(evt);
            }
        });
        menuagent.add(btnAgentExit);

        jMenuBar1.add(menuagent);

        menucaretaker.setText("Caretaker");

        jMenu2.setText("Tasks");

        menuCaretakerAccounting.setText("Accounting");

        menuCaretakerArrears.setText("Arrears");
        menuCaretakerArrears.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCaretakerArrearsActionPerformed(evt);
            }
        });
        menuCaretakerAccounting.add(menuCaretakerArrears);
        menuCaretakerAccounting.add(jSeparator27);

        menuCaretakerExpenditure.setText("Expenditure");
        menuCaretakerExpenditure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCaretakerExpenditureActionPerformed(evt);
            }
        });
        menuCaretakerAccounting.add(menuCaretakerExpenditure);
        menuCaretakerAccounting.add(jSeparator28);

        menuCaretakerRentPayment.setText("Rent Payment");
        menuCaretakerRentPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCaretakerRentPaymentActionPerformed(evt);
            }
        });
        menuCaretakerAccounting.add(menuCaretakerRentPayment);
        menuCaretakerAccounting.add(jSeparator29);

        jMenu2.add(menuCaretakerAccounting);
        jMenu2.add(jSeparator41);

        menuCaretakerHunits.setText("Housing units");
        menuCaretakerHunits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCaretakerHunitsActionPerformed(evt);
            }
        });
        jMenu2.add(menuCaretakerHunits);
        jMenu2.add(jSeparator40);

        menuCaretakerNewTenant.setText("New Tenant");
        menuCaretakerNewTenant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCaretakerNewTenantActionPerformed(evt);
            }
        });
        jMenu2.add(menuCaretakerNewTenant);
        jMenu2.add(jSeparator39);

        menuCaretakerProperty.setText("Property");
        menuCaretakerProperty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCaretakerPropertyActionPerformed(evt);
            }
        });
        jMenu2.add(menuCaretakerProperty);
        jMenu2.add(jSeparator38);

        menuCaretakerTenants.setText("Tenants");
        menuCaretakerTenants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCaretakerTenantsActionPerformed(evt);
            }
        });
        jMenu2.add(menuCaretakerTenants);
        jMenu2.add(jSeparator37);

        jMenu9.setText("Print");

        menuCaretakerPayments.setText("Print Receipt");
        menuCaretakerPayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCaretakerPaymentsActionPerformed(evt);
            }
        });
        jMenu9.add(menuCaretakerPayments);
        jMenu9.add(jSeparator36);

        menuCaretakerRentDefaultNotice.setText("Print Rent Default Notice");
        menuCaretakerRentDefaultNotice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCaretakerRentDefaultNoticeActionPerformed(evt);
            }
        });
        jMenu9.add(menuCaretakerRentDefaultNotice);

        jMenu2.add(jMenu9);
        jMenu2.add(jSeparator45);

        menuCaretakerIDVerification.setText("ID Verification");
        menuCaretakerIDVerification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCaretakerIDVerificationActionPerformed(evt);
            }
        });
        jMenu2.add(menuCaretakerIDVerification);

        menucaretaker.add(jMenu2);
        menucaretaker.add(jSeparator22);

        menuCaretakerExit.setText("Exit");
        menuCaretakerExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCaretakerExitActionPerformed(evt);
            }
        });
        menucaretaker.add(menuCaretakerExit);

        jMenuBar1.add(menucaretaker);

        menuAbout.setText("About");
        menuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutActionPerformed(evt);
            }
        });

        btnAboutBracestate.setText("About - Bracestate");
        btnAboutBracestate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutBracestateActionPerformed(evt);
            }
        });
        menuAbout.add(btnAboutBracestate);

        jMenuBar1.add(menuAbout);

        menuHelp.setText("Help");

        jMenuItem15.setText("User Manual");
        menuHelp.add(jMenuItem15);
        menuHelp.add(jSeparator20);

        jMenuItem19.setText("Check for Updates");
        menuHelp.add(jMenuItem19);

        jMenuBar1.add(menuHelp);

        menuLogout.setText("Logout");

        menuSignOut.setText("Sign Out");
        menuSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSignOutActionPerformed(evt);
            }
        });
        menuLogout.add(menuSignOut);

        jMenuBar1.add(menuLogout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuAdminPropertyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdminPropertyActionPerformed
        Property prop = new Property();
        prop.show();
    }//GEN-LAST:event_menuAdminPropertyActionPerformed

    private void menuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutActionPerformed

    }//GEN-LAST:event_menuAboutActionPerformed

    private void btnAccountantArrearsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountantArrearsActionPerformed

        ArrearsUsers arrears =  new ArrearsUsers();
        arrears.show();
    }//GEN-LAST:event_btnAccountantArrearsActionPerformed

    private void btnAccountantExpenditureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountantExpenditureActionPerformed
        AccountantExpenditure exp = new AccountantExpenditure();
        exp.show();
    }//GEN-LAST:event_btnAccountantExpenditureActionPerformed

    private void btnAccountantRentPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountantRentPaymentActionPerformed
        Accounting accounts = new Accounting();
        accounts.show();
    }//GEN-LAST:event_btnAccountantRentPaymentActionPerformed

    private void btnAccountantPrintReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountantPrintReceiptActionPerformed
        Payment pay = new Payment();
        pay.show();
    }//GEN-LAST:event_btnAccountantPrintReceiptActionPerformed

    private void btnAccountantDefaultNoticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountantDefaultNoticeActionPerformed
        DefaultNotice defaN = new DefaultNotice();
        defaN.show();
    }//GEN-LAST:event_btnAccountantDefaultNoticeActionPerformed

    private void btnAboutBracestateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutBracestateActionPerformed

        About about = new About();
        about.show();
    }//GEN-LAST:event_btnAboutBracestateActionPerformed

    private void menuAccExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAccExitActionPerformed
        int log = JOptionPane.showConfirmDialog(this, "Exit Bracestate? \n\nBracestate is now Saving your work and shutting down!", "Confirm exit", JOptionPane.YES_NO_OPTION);

        if (log == JOptionPane.YES_OPTION) {
            this.dispose();
        }
        
    }//GEN-LAST:event_menuAccExitActionPerformed

    private void menuAdminArrearsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdminArrearsActionPerformed

        Arrears arrears = null;
        try {
            arrears = new Arrears();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Roles.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Roles.class.getName()).log(Level.SEVERE, null, ex);
        }
        arrears.show();
    }//GEN-LAST:event_menuAdminArrearsActionPerformed

    private void menuAdminExpenditureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdminExpenditureActionPerformed
        Expenditures exp = new Expenditures();
        exp.show();
    }//GEN-LAST:event_menuAdminExpenditureActionPerformed

    private void menuAdminRentPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdminRentPaymentActionPerformed
        Accounting accs = new Accounting();
        accs.show();
    }//GEN-LAST:event_menuAdminRentPaymentActionPerformed

    private void menuAdminIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdminIncomeActionPerformed
        Income inc = new Income();
        inc.show();
    }//GEN-LAST:event_menuAdminIncomeActionPerformed

    private void menuAdminHunitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdminHunitsActionPerformed
        Housingunit hunits = new Housingunit();
        hunits.show();
    }//GEN-LAST:event_menuAdminHunitsActionPerformed

    private void menuNewTenantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNewTenantActionPerformed
        NewTenant newT = new NewTenant();
        newT.show();
    }//GEN-LAST:event_menuNewTenantActionPerformed

    private void menuAdminTenantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdminTenantsActionPerformed
        DisplayTenants dip = new DisplayTenants();
        dip.show();
    }//GEN-LAST:event_menuAdminTenantsActionPerformed

    private void menuAdminPaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdminPaymentsActionPerformed
        Payment pay = new Payment();
        pay.show();
    }//GEN-LAST:event_menuAdminPaymentsActionPerformed

    private void menuAdminRentDefaultNoticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdminRentDefaultNoticeActionPerformed
        DefaultNotice def = new DefaultNotice();
        def.show();
    }//GEN-LAST:event_menuAdminRentDefaultNoticeActionPerformed

    private void menuAdminCreateuserAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdminCreateuserAccountActionPerformed
        CreateAccount createAcc = new CreateAccount();
        createAcc.show();
    }//GEN-LAST:event_menuAdminCreateuserAccountActionPerformed

    private void btnAdminExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminExitActionPerformed
        int log = JOptionPane.showConfirmDialog(this, "Exit Bracestate? \n\nBracestate is now Saving your work and shutting down!", "Confirm exit", JOptionPane.YES_NO_OPTION);

        if (log == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_btnAdminExitActionPerformed

    private void menuAgentArrearsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgentArrearsActionPerformed
        ArrearsUsers arrears = new ArrearsUsers();
        arrears.show();
    }//GEN-LAST:event_menuAgentArrearsActionPerformed

    private void menuAgentExpenditureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgentExpenditureActionPerformed
        AccountantExpenditure accExp = new AccountantExpenditure();
        accExp.show();
    }//GEN-LAST:event_menuAgentExpenditureActionPerformed

    private void menuAgentRentPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgentRentPaymentActionPerformed
        Accounting acc = new Accounting();
        acc.show();
    }//GEN-LAST:event_menuAgentRentPaymentActionPerformed

    private void btnAgentExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgentExitActionPerformed
        int log = JOptionPane.showConfirmDialog(this, "Exit Bracestate? \n\nBracestate is now Saving your work and shutting down!", "Confirm exit", JOptionPane.YES_NO_OPTION);

        if (log == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_btnAgentExitActionPerformed

    private void menuCaretakerArrearsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCaretakerArrearsActionPerformed
        ArrearsUsers arrears = new ArrearsUsers();
        arrears.show();
    }//GEN-LAST:event_menuCaretakerArrearsActionPerformed

    private void menuCaretakerExpenditureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCaretakerExpenditureActionPerformed
        AccountantExpenditure exp = new AccountantExpenditure();
        exp.show();
    }//GEN-LAST:event_menuCaretakerExpenditureActionPerformed

    private void menuCaretakerRentPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCaretakerRentPaymentActionPerformed
        Accounting acc = new Accounting();
        acc.show();
    }//GEN-LAST:event_menuCaretakerRentPaymentActionPerformed

    private void menuAgentHunitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgentHunitsActionPerformed
        Housingunit hunit = new Housingunit();
        hunit.show();
    }//GEN-LAST:event_menuAgentHunitsActionPerformed

    private void menuAgentNewTenantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgentNewTenantActionPerformed
        NewTenant nT = new NewTenant();
        nT.show();
    }//GEN-LAST:event_menuAgentNewTenantActionPerformed

    private void menuAgentPropertyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgentPropertyActionPerformed
        Property prop = new Property();
        prop.show();
    }//GEN-LAST:event_menuAgentPropertyActionPerformed

    private void menuAgentTenantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgentTenantsActionPerformed
        DisplayTenants disp = new DisplayTenants();
        disp.show();
    }//GEN-LAST:event_menuAgentTenantsActionPerformed

    private void menuAgentPaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgentPaymentsActionPerformed
        Payment pay = new Payment();
        pay.show();
    }//GEN-LAST:event_menuAgentPaymentsActionPerformed

    private void menuAgentRentDefaultNoticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgentRentDefaultNoticeActionPerformed
        DefaultNotice def = new DefaultNotice();
        def.show();
    }//GEN-LAST:event_menuAgentRentDefaultNoticeActionPerformed

    private void menuCaretakerHunitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCaretakerHunitsActionPerformed
        Housingunit hunit = new Housingunit();
        hunit.show();
    }//GEN-LAST:event_menuCaretakerHunitsActionPerformed

    private void menuCaretakerNewTenantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCaretakerNewTenantActionPerformed
        NewTenant nT = new NewTenant();
        nT.show();
    }//GEN-LAST:event_menuCaretakerNewTenantActionPerformed

    private void menuCaretakerPropertyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCaretakerPropertyActionPerformed
        Property prop = new Property();
        prop.show();
    }//GEN-LAST:event_menuCaretakerPropertyActionPerformed

    private void menuCaretakerTenantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCaretakerTenantsActionPerformed
        DisplayTenants disp = new DisplayTenants();
        disp.show();
    }//GEN-LAST:event_menuCaretakerTenantsActionPerformed

    private void menuCaretakerPaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCaretakerPaymentsActionPerformed
        Payment pay = new Payment();
        pay.show();
    }//GEN-LAST:event_menuCaretakerPaymentsActionPerformed

    private void menuCaretakerRentDefaultNoticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCaretakerRentDefaultNoticeActionPerformed
        DefaultNotice def = new DefaultNotice();
        def.show();
    }//GEN-LAST:event_menuCaretakerRentDefaultNoticeActionPerformed

    private void menuCaretakerExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCaretakerExitActionPerformed
        int log = JOptionPane.showConfirmDialog(this, "Exit Bracestate? \n\nBracestate is now Saving your work and shutting down!", "Confirm exit", JOptionPane.YES_NO_OPTION);

        if (log == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_menuCaretakerExitActionPerformed

    private void menuSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSignOutActionPerformed
        this.dispose();
        lRoles.show();
    }//GEN-LAST:event_menuSignOutActionPerformed

    private void menuAccountantIDVerificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAccountantIDVerificationActionPerformed
        IDDisplay idDisplay = new IDDisplay();
        idDisplay.show();
    }//GEN-LAST:event_menuAccountantIDVerificationActionPerformed

    private void menuAdminIDVerificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdminIDVerificationActionPerformed
        IDDisplay idDisplay = new IDDisplay();
        idDisplay.show();
    }//GEN-LAST:event_menuAdminIDVerificationActionPerformed

    private void menuAgentIDVerificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgentIDVerificationActionPerformed
        IDDisplay idDisplay = new IDDisplay();
        idDisplay.show();
    }//GEN-LAST:event_menuAgentIDVerificationActionPerformed

    private void menuCaretakerIDVerificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCaretakerIDVerificationActionPerformed
        IDDisplay idDisplay = new IDDisplay();
        idDisplay.show();
    }//GEN-LAST:event_menuCaretakerIDVerificationActionPerformed

    private void menuAdminChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdminChangePasswordActionPerformed
        ChangePassword change = new ChangePassword();
        change.show();
    }//GEN-LAST:event_menuAdminChangePasswordActionPerformed

    private void menuAccountantNewTenantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAccountantNewTenantActionPerformed
        NewTenant nT = new NewTenant();
        nT.show();
    }//GEN-LAST:event_menuAccountantNewTenantActionPerformed

    private void menuAdminPaymentsReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdminPaymentsReportActionPerformed
        DisplayPaymentPrint pPrint = new DisplayPaymentPrint();
        pPrint.show();
    }//GEN-LAST:event_menuAdminPaymentsReportActionPerformed

    private void menuAdminExpenditureReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdminExpenditureReportActionPerformed
        DisplayExpenditureAdmin eAd = new DisplayExpenditureAdmin();
        eAd.show();
    }//GEN-LAST:event_menuAdminExpenditureReportActionPerformed

    private void menuAdminArrearsReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdminArrearsReportActionPerformed
        Arrears arr = null;
        try {
            arr = new Arrears();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Roles.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Roles.class.getName()).log(Level.SEVERE, null, ex);
        }
        arr.show();
    }//GEN-LAST:event_menuAdminArrearsReportActionPerformed

    private void menuAccountantHunitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAccountantHunitsActionPerformed
        Housingunit hu = new Housingunit();
        hu.show();
    }//GEN-LAST:event_menuAccountantHunitsActionPerformed

    private void menuAccountanttPropertyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAccountanttPropertyActionPerformed
        Property prop = new Property();
        prop.show();
    }//GEN-LAST:event_menuAccountanttPropertyActionPerformed

    private void menuAccounantTenantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAccounantTenantsActionPerformed
        DisplayTenants tenants = new DisplayTenants();
        tenants.show();
    }//GEN-LAST:event_menuAccounantTenantsActionPerformed

    /**
     * @param userRole
     * @param args the command line arguments
     */
    public void displayMenu(String userRole) {

        Roles roles = new Roles();

        switch (userRole) {
            case "Admin":
                menuAdmin.setVisible(true);
                menuagent.setVisible(true);
                menucaretaker.setVisible(true);
                menuAccountant.setVisible(true);
                menuAbout.setVisible(true);
                menuHelp.setVisible(true);
                break;
            case "Agent":
                menuagent.setVisible(true);
                menuAdmin.setVisible(false);
                menucaretaker.setVisible(false);
                menuAccountant.setVisible(false);
                menuAbout.setVisible(true);
                menuHelp.setVisible(true);
                break;
            case "Caretaker":
                menuagent.setVisible(false);
                menuAdmin.setVisible(false);
                menucaretaker.setVisible(true);
                menuAccountant.setVisible(false);
                menuAbout.setVisible(true);
                menuHelp.setVisible(true);
                break;
            case "Accountant":
                menuagent.setVisible(false);
                menuAdmin.setVisible(false);
                menucaretaker.setVisible(false);
                menuAccountant.setVisible(true);
                menuAbout.setVisible(true);
                menuHelp.setVisible(true);
                break;
            default:
                JOptionPane.showMessageDialog(this, "Error!, Unavailable User Account!");
                break;
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Roles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Roles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Roles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Roles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Roles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnAboutBracestate;
    private javax.swing.JMenu btnAccountantAccounting;
    private javax.swing.JMenuItem btnAccountantArrears;
    private javax.swing.JMenuItem btnAccountantDefaultNotice;
    private javax.swing.JMenuItem btnAccountantExpenditure;
    private javax.swing.JMenuItem btnAccountantPrintReceipt;
    private javax.swing.JMenuItem btnAccountantRentPayment;
    private javax.swing.JMenu btnAccountantTasks;
    private javax.swing.JMenuItem btnAdminExit;
    private javax.swing.JMenuItem btnAgentExit;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator15;
    private javax.swing.JPopupMenu.Separator jSeparator16;
    private javax.swing.JPopupMenu.Separator jSeparator17;
    private javax.swing.JPopupMenu.Separator jSeparator18;
    private javax.swing.JPopupMenu.Separator jSeparator19;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator20;
    private javax.swing.JPopupMenu.Separator jSeparator21;
    private javax.swing.JPopupMenu.Separator jSeparator22;
    private javax.swing.JPopupMenu.Separator jSeparator23;
    private javax.swing.JPopupMenu.Separator jSeparator24;
    private javax.swing.JPopupMenu.Separator jSeparator25;
    private javax.swing.JPopupMenu.Separator jSeparator26;
    private javax.swing.JPopupMenu.Separator jSeparator27;
    private javax.swing.JPopupMenu.Separator jSeparator28;
    private javax.swing.JPopupMenu.Separator jSeparator29;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator30;
    private javax.swing.JPopupMenu.Separator jSeparator31;
    private javax.swing.JPopupMenu.Separator jSeparator32;
    private javax.swing.JPopupMenu.Separator jSeparator33;
    private javax.swing.JPopupMenu.Separator jSeparator34;
    private javax.swing.JPopupMenu.Separator jSeparator35;
    private javax.swing.JPopupMenu.Separator jSeparator36;
    private javax.swing.JPopupMenu.Separator jSeparator37;
    private javax.swing.JPopupMenu.Separator jSeparator38;
    private javax.swing.JPopupMenu.Separator jSeparator39;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator40;
    private javax.swing.JPopupMenu.Separator jSeparator41;
    private javax.swing.JPopupMenu.Separator jSeparator42;
    private javax.swing.JPopupMenu.Separator jSeparator43;
    private javax.swing.JPopupMenu.Separator jSeparator44;
    private javax.swing.JPopupMenu.Separator jSeparator45;
    private javax.swing.JPopupMenu.Separator jSeparator46;
    private javax.swing.JPopupMenu.Separator jSeparator47;
    private javax.swing.JPopupMenu.Separator jSeparator48;
    private javax.swing.JPopupMenu.Separator jSeparator49;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator50;
    private javax.swing.JPopupMenu.Separator jSeparator51;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JMenu menuAbout;
    private javax.swing.JMenuItem menuAccExit;
    private javax.swing.JMenuItem menuAccounantTenants;
    private javax.swing.JMenu menuAccountant;
    private javax.swing.JMenuItem menuAccountantHunits;
    private javax.swing.JMenuItem menuAccountantIDVerification;
    private javax.swing.JMenuItem menuAccountantNewTenant;
    private javax.swing.JMenuItem menuAccountanttProperty;
    public javax.swing.JMenu menuAdmin;
    private javax.swing.JMenuItem menuAdminArrears;
    private javax.swing.JMenuItem menuAdminArrearsReport;
    private javax.swing.JMenuItem menuAdminChangePassword;
    private javax.swing.JMenuItem menuAdminCreateuserAccount;
    private javax.swing.JMenuItem menuAdminExpenditure;
    private javax.swing.JMenuItem menuAdminExpenditureReport;
    private javax.swing.JMenuItem menuAdminHunits;
    private javax.swing.JMenuItem menuAdminIDVerification;
    private javax.swing.JMenuItem menuAdminIncome;
    private javax.swing.JMenuItem menuAdminPayments;
    private javax.swing.JMenuItem menuAdminPaymentsReport;
    private javax.swing.JMenuItem menuAdminProperty;
    private javax.swing.JMenuItem menuAdminRentDefaultNotice;
    private javax.swing.JMenuItem menuAdminRentPayment;
    private javax.swing.JMenuItem menuAdminTenants;
    private javax.swing.JMenuItem menuAgentArrears;
    private javax.swing.JMenuItem menuAgentExpenditure;
    private javax.swing.JMenuItem menuAgentHunits;
    private javax.swing.JMenuItem menuAgentIDVerification;
    private javax.swing.JMenuItem menuAgentNewTenant;
    private javax.swing.JMenuItem menuAgentPayments;
    private javax.swing.JMenuItem menuAgentProperty;
    private javax.swing.JMenuItem menuAgentRentDefaultNotice;
    private javax.swing.JMenuItem menuAgentRentPayment;
    private javax.swing.JMenuItem menuAgentTenants;
    private javax.swing.JMenu menuCaretakerAccounting;
    private javax.swing.JMenuItem menuCaretakerArrears;
    private javax.swing.JMenuItem menuCaretakerExit;
    private javax.swing.JMenuItem menuCaretakerExpenditure;
    private javax.swing.JMenuItem menuCaretakerHunits;
    private javax.swing.JMenuItem menuCaretakerIDVerification;
    private javax.swing.JMenuItem menuCaretakerNewTenant;
    private javax.swing.JMenuItem menuCaretakerPayments;
    private javax.swing.JMenuItem menuCaretakerProperty;
    private javax.swing.JMenuItem menuCaretakerRentDefaultNotice;
    private javax.swing.JMenuItem menuCaretakerRentPayment;
    private javax.swing.JMenuItem menuCaretakerTenants;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenu menuLogout;
    private javax.swing.JMenuItem menuNewTenant;
    private javax.swing.JMenuItem menuSignOut;
    private javax.swing.JMenu menuagent;
    private javax.swing.JMenu menucaretaker;
    // End of variables declaration//GEN-END:variables
}
